import type { Metadata } from "next";
import "./globals.css";
import { Nunito, Nunito_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import { AuthProvider } from "@/features/auth/AuthProvider";

const nunitoSans = Nunito_Sans({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full antialiased", "font-sans", nunitoSans.variable)}
    >
      <body suppressHydrationWarning>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
